USE master;
CREATE TABLE CITY(ID INT PRIMARY KEY,CITY_NAME VARCHAR(20));
INSERT INTO CITY VALUES(1,'PUNE'),(2,'MUMBAI'),(3,'GOA');
CREATE TABLE STUDENT1(ID INT PRIMARY KEY,NAME VARCHAR(25),CITY_ID INT,CITYNAME VARCHAR(25),
FOREIGN KEY (CITY_ID) REFERENCES CITY(ID) ON UPDATE CASCADE);
INSERT INTO STUDENT1 VALUES(101,'AHMAD',1,'PUNE'),(102,'SHER',2,'MUMBAI'),(103,'HAROON',1,'PUNE'),
(104,'HERO',3,'MUMBAI');
SELECT * FROM STUDENT1;
UPDATE CITY SET ID=5 WHERE CITY_NAME='PUNE';
SELECT * FROM STUDENT1 as s
LEFT JOIN CITY as c
on s.CITY_ID=c.ID;
DROP TABLE STUDENT1;
DROP TABLE STUDENT1;
DELETE FROM STUDENT1 WHERE ID=101;
ALTER TABLE STUDENT1 ADD GRADE VARCHAR(20);
ALTER TABLE STUDENT1
DROP GRADE;
UPDATE STUDENT1 SET HERO='GG';
--ADDING COLUMN
ALTER TABLE Student1 
ADD CLASS INT;  
--DELETING COLUMN
ALTER TABLE STUDENT1 MODIFY HERO VARCHAR(2);
ALTER TABLE Student1 
DROP COLUMN CLASS; 
ALTER TABLE STUDENT1
RENAME TO STUDENT10;


