--CREATE DATABASE HERO;
--DROP DATABASE HERO;
CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE STUDENT(ROLLNO int PRIMARY KEY check (ROLLNO>18),Name VARCHAR(30),
 MARKS INT CHECK (MARKS>50),GRADE VARCHAR(2) DEFAULT 'A',CITY VARCHAR(20));
INSERT INTO STUDENT VALUES(19,'Adam',55,'B','DELHI'),(20,'AGHam',57,'B','MUMBAI'),
(21,'AHamD',60,'BB','DELHI'),(22,'BAdam',65,'C','GOA');
SELECT * FROM STUDENT;
UPDATE STUDENT SET GRADE='B' WHERE ROLLNO=21;
--SELECT * FROM STUDENT WHERE MARKS>60 OR GRADE='B';
--SELECT MIN(MARKS) FROM STUDENT;
--SELECT ROLLNO,NAME FROM STUDENT;
--SELECT * FROM STUDENT WHERE MARKS BETWEEN 60 AND 70;
--SELECT * FROM STUDENT WHERE MARKS IN(55,57,60,65);
--SELECT * FROM STUDENT WHERE MARKS NOT IN(55,57,60);
--DROP TABLE student;
SELECT * FROM STUDENT ORDER BY MARKS DESC;
SELECT * FROM STUDENT ORDER BY GRADE ASC;
SELECT AVG(MARKS) FROM STUDENT;
SELECT SUM(MARKS) FROM STUDENT;
SELECT COUNT(marks) from student;
SELECT SUM(MARKS)/COUNT(MARKS) FROM STUDENT;
SELECT CITY,avg(marks) FROM STUDENT GROUP BY city order by avg(marks) ASC;
SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY city ORDER BY CITY DESC;
-- order by MARKS ASC;
SELECT GRADE,COUNT(ROLLNO) FROM STUDENT GROUP BY GRADE HAVING GRADE='C';
CREATE TABLE EMPLOYEE5(SSN CHAR(9) PRIMARY KEY,NAME VARCHAR(10));
INSERT INTO EMPLOYEE5 VALUES(1,'AHMAD');
CREATE TABLE DEPENDENT4(NAME VARCHAR(20),EMPLOYEESSN CHAR(9),
FOREIGN KEY(EMPLOYEESSN) REFERENCES EMPLOYEE5(SSN) ON DELETE CASCADE ON UPDATE CASCADE,
SEX CHAR(2) check (SEX IN('M','m','F','f')));
INSERT INTO DEPENDENT4 VALUES('AHMAD',1,'F');
UPDATE EMPLOYEE5 SET SSN=5 WHERE NAME='AHMAD';
DROP TABLE EMPLOYEE5;
DROP TABLE DEPENDENT1;
SELECT * FROM DEPENDENT4;
SELECT * FROM EMPLOYEE5;

