CREATE TABLE EMPLOYEE4(ID INT PRIMARY KEY,NAME VARCHAR(30),SALARY INT,City VARCHAR(50));
INSERT INTO EMPLOYEE4 VALUES(101,'Adam',25000,'Gujrat'),(102,'Sohaib',4000,'Gujrat'),
(103,'Zahid',50000,'Gujrat');
SELECT * FROM EMPLOYEE4;
CREATE TABLE DEPENDENT(GENDER VARCHAR(10) CHECK (GENDER IN('M','F','m','f')),Employee_SSN CHAR(9));
SELECT SALARY,COUNT(ID) FROM EMPLOYEE4 GROUP BY SALARY;
UPDATE EMPLOYEE4 SET NAME='Choudhry' where name='Sohaib';

CREATE TABLE DEPARTMENT1(ID INT PRIMARY KEY,NAME VARCHAR(25));
INSERT INTO DEPARTMENT1 VALUES(101,'ENGLISH'),(102,'MMATHEMATICS');
SELECT * FROM DEPARTMENT1;
CREATE TABLE TEACHER(ID INT PRIMARY KEY,NAME VARCHAR(25),DEPT_ID INT,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT1(ID) ON UPDATE CASCADE ON DELETE CASCADE);
INSERT INTO TEACHER VALUES(101,'ENGLISH',101),(102,'MMATHEMATICS',102);
SELECT * FROM TEACHER;
UPDATE DEPARTMENT1 SET ID=105 WHERE ID=101;


