USE MASTER;
CREATE TABLE CITY1(ID INT,CITY_NAME VARCHAR(20));
INSERT INTO CITY1 VALUES(7,'PUNE'),(8,'MUMBAI'),(9,'GOA');
SELECT * FROM CITY1;
--ADD COLUMN
ALTER TABLE CITY1
ADD DESIGNATION VARCHAR(25);
--DELETING COLUMN
ALTER TABLE CITY1
DROP COLUMN DESIGNATION;
ALTER TABLE CITY1
CHANGE DESIGNATION DESIG INT;
ALTER TABLE CITY1
RENAME TO CITY2;
ALTER TABLE CITY1
RENAME CITY1 TO CITY2;
